import { brandLogo } from '../lib/brand.mjs';
import { loadJSON,e,icon,anchor,action,routeIndex } from '../lib/site.mjs';
const T={de:{nav:'Hauptnavigation',open:'öffnen',close:'schließen',menu:'Menü',enquiry:'Diskrete Anfrage',overview:['Alle Themen','Alle Leistungen','Länderübersicht','Über die Arbeitsweise'],kicker:['Wissen und Vorbereitung','Planung, Umsetzung und Betreuung','Information oder persönliche Auswahl','Das Unternehmen'],headline:['Dein Plan B beginnt mit den richtigen Fragen.','Welche Arbeit möchtest du abgeben?','Zwei Wege. Zwei unterschiedliche Aufgaben.','Persönlich geführt. Klar vereinbart.'],countryKicker:['Selbst informieren','Persönlich beauftragen'],countryAction:['Zu den Länderprofilen','Zum Auswahlauftrag'],serviceNote:'Einzelaufträge sind direkt möglich. Ein Orientierungsgespräch oder eine Erstklärung ist keine Pflicht.',intro:'Deine nächste Vorbereitung beginnt mit deinem Anliegen.',switch:'Sprache wechseln',home:'Startseite',company:'Unternehmen',legal:'Rechtliches',topic:'Dein Anliegen',back:'Nach oben',copyright:'Alle Rechte vorbehalten.'},en:{nav:'Main navigation',open:'open',close:'close',menu:'Menu',enquiry:'Private enquiry',overview:['All topics','All services','Country overview','How we work'],kicker:['Knowledge and preparation','Planning, implementation and support','Information or personal selection','The company'],headline:['Your Plan B starts with the right questions.','What would you like us to take care of?','Two routes. Two different tasks.','Personally managed. Clearly agreed.'],countryKicker:['Research for yourself','Commission a personal comparison'],countryAction:['Explore country profiles','See the selection service'],serviceNote:'You can commission individual tasks directly. An orientation call or initial assessment is not a prerequisite.',intro:'Start with the arrangements you want to prepare.',switch:'Change language',home:'homepage',company:'Company',legal:'Legal information',topic:'Your enquiry',back:'Back to top',copyright:'All rights reserved.'}};
function flag(lang,current,translation){
 const route=lang===current?`/${lang}/`:(translation||`/${lang}/`);
 const language=lang==='de'?'Deutsch':'English';
 const label=language+(!translation&&lang!==current?(lang==='de'?': Startseite':': homepage'):'');
 if(lang===current)return `<span class="exb6-flag" aria-current="true" aria-label="${language}"><img src="/assets/flag-${lang}.svg" width="24" height="16" alt=""/><span class="exb-sr-only">${language}</span></span>`;
 return `<a href="${e(route)}" data-route="${e(route)}" class="exb6-flag" lang="${lang}" hreflang="${lang}" aria-label="${e(label)}"><img src="/assets/flag-${lang}.svg" width="24" height="16" alt=""/><span class="exb-sr-only">${e(label)}</span></a>`;
}
export function flags(page){return `<div class="exb6-flags" role="group" aria-label="${T[page.lang].switch}">${flag('de',page.lang,page.translation)}${flag('en',page.lang,page.translation)}</div>`;}
function menuLink(link){return anchor(link.route,`<span class="exb6-menu-link-copy"><span class="exb6-menu-link-title">${e(link.label)}</span><span class="exb6-menu-link-description">${e(link.description)}</span></span>${icon('arrow')}`,'exb6-menu-link');}
function panel(root,i,t){
 const heading=`<div class="exb6-panel-heading"><div><p class="exb6-kicker">${t.kicker[i]}</p><p class="exb6-panel-title">${t.headline[i]}</p></div>${anchor(root.route,t.overview[i]+icon('arrow'),'exb6-overview')}</div>`;
 let body='';
 if(i===1){
  const tabs=root.groups.map((g,j)=>`<button class="exb6-service-tab" type="button" id="exb6-tab-${j}" role="tab" aria-selected="${j===0}" tabindex="${j===0?0:-1}" aria-controls="exb6-service-${j}">${icon(g.icon||'file')}<span><strong>${e(g.label)}</strong><span>${e(g.description)}</span></span>${icon('chevron')}</button>`).join('');
  const panels=root.groups.map((g,j)=>`<div role="tabpanel" id="exb6-service-${j}" aria-labelledby="exb6-tab-${j}"${j===0?'':' hidden'}><p class="exb6-service-panel-label">${e(g.label)}</p><div class="exb6-service-links">${g.links.map(menuLink).join('')}</div></div>`).join('');
  body=`<div class="exb6-services-layout"><div class="exb6-service-tabs" role="tablist" aria-orientation="vertical" aria-label="${e(root.label)}">${tabs}</div><div class="exb6-service-panels">${panels}</div></div><p class="exb6-panel-note">${t.serviceNote}</p>`;
 }else if(i===2){body=`<div class="exb6-country-choices">${root.groups[0].links.map((l,j)=>anchor(l.route,`<span class="exb6-choice-icon">${icon(j===0?'globe':'compass')}</span><span class="exb6-kicker">${t.countryKicker[j]}</span><span class="exb6-choice-title">${e(l.label)}</span><span class="exb6-choice-description">${e(l.description)}</span><span class="exb6-choice-cta">${t.countryAction[j]}${icon('arrow')}</span>`,'exb6-country-choice')).join('')}</div>`;}
 else body=`<div class="exb6-simple-links">${root.groups.flatMap(g=>g.links).map(menuLink).join('')}</div>`;
 return `<div class="exb6-panel" id="exb6-menu-${i}" hidden>${heading}${body}</div>`;
}
export function header(page){
 const t=T[page.lang], nav=loadJSON(`src/data/navigation-${page.lang}.json`),home=`/${page.lang}/`,contact=page.lang==='de'?'/de/anfrage/':'/en/enquiry/';
 return `<header class="exb-header exb-dark exb-header-v6"><div class="exb-wrap exb6-header-inner">${anchor(home,brandLogo(page,{responsive:true}),'exb-brand')}<nav class="exb6-nav" aria-label="${t.nav}"><ul class="exb6-nav-list">${nav.map((r,i)=>`<li class="exb6-nav-item"><div class="exb6-nav-head">${anchor(r.route,`<span data-nav-label>${e(r.label)}</span>`,'exb6-root-link')}<button type="button" class="exb6-menu-toggle" aria-label="${e(r.label)}: ${t.open}" aria-expanded="false" aria-controls="exb6-menu-${i}">${icon('chevron')}</button></div>${panel(r,i,t)}</li>`).join('')}</ul></nav><div class="exb6-actions">${flags(page)}${action(contact,t.enquiry,'exb-btn exb6-header-cta')}<button type="button" id="exb6-mobile-trigger" class="exb6-mobile-trigger" aria-controls="exb6-mobile-menu" aria-expanded="false" aria-label="${t.menu}: ${t.open}">${icon('menu')}</button></div></div></header>`;
}
export function mobile(page){
 const t=T[page.lang], nav=loadJSON(`src/data/navigation-${page.lang}.json`),contact=page.lang==='de'?'/de/anfrage/':'/en/enquiry/';
 const sections=nav.map((root,i)=>{
 const links=i===1?root.groups.map(g=>`<details class="exb6-mobile-subgroup"><summary>${icon(g.icon||'file')}<span>${e(g.label)}</span>${icon('chevron')}</summary><div>${g.links.map(menuLink).join('')}</div></details>`).join(''):root.groups.flatMap(g=>g.links).map(menuLink).join('');
 return `<section class="exb6-mobile-section"><div class="exb6-mobile-section-head">${anchor(root.route,`<span data-nav-label>${e(root.label)}</span>`,'')}<button type="button" class="exb6-mobile-section-toggle" aria-label="${e(root.label)}: ${t.open}" aria-expanded="false" aria-controls="exb6-mobile-group-${i}">${icon('chevron')}</button></div><div class="exb6-mobile-section-body" id="exb6-mobile-group-${i}" hidden>${anchor(root.route,t.overview[i]+icon('arrow'),'exb6-mobile-overview')}${links}</div></section>`;
 }).join('');
 return `<dialog id="exb6-mobile-menu" class="exb6-mobile-dialog exb-dark" aria-label="${t.menu}"><div class="exb6-mobile-top">${anchor(`/${page.lang}/`,brandLogo(page,{mobile:true}),'exb-brand')}<button id="exb6-mobile-close" type="button" class="exb6-mobile-close" aria-label="${t.menu}: ${t.close}">${icon('close')}</button></div><div class="exb6-mobile-intro"><p>${t.intro}</p>${action(contact,t.enquiry)}</div><nav aria-label="${t.nav}">${sections}</nav><div class="exb6-mobile-language">${flags(page)}</div></dialog>`;
}
export function footer(page){
 const de=page.lang==='de',t=T[page.lang];
 const groups=de?[[['/de/arbeitsweise/','Arbeitsweise'],['/de/diskretion/','Diskretion und Verantwortung'],['/de/zusammenarbeit/','Fachliche Zusammenarbeit']],[['/de/anbieterinformationen/','Anbieterinformationen'],['/de/datenschutz/','Datenschutz'],['/de/leistungsbedingungen/','Leistungs- und Vertragsbedingungen']]]:[[['/en/how-we-work/','How we work'],['/en/discretion/','Discretion and responsibility'],['/en/collaboration/','Specialist collaboration']],[['/en/provider-information/','Provider information'],['/en/privacy/','Privacy notice'],['/en/service-terms/','Service and contract terms']]];
 return `<footer class="exb-footer exb-dark" aria-label="${de?'Seitenfooter':'Page footer'}"><div class="exb-wrap"><div class="exb-footer-grid"><div class="exb-footer-brand">${anchor(`/${page.lang}/`,brandLogo(page),'exb-brand')}<p>${de?'Eine eigene Basis.<br>Außerhalb des Herkunftslands.':'Your own base.<br>Beyond your home country.'}</p></div>${groups.map((g,i)=>`<nav class="exb-footer-group" aria-label="${i?t.legal:t.company}"><p class="exb-footer-label">${i?t.legal:t.company}</p><ul>${g.map(([r,l])=>`<li>${anchor(r,e(l),'')}</li>`).join('')}</ul></nav>`).join('')}<div class="exb-footer-contact"><p class="exb-footer-label">${t.topic}</p>${action(de?'/de/anfrage/':'/en/enquiry/',t.enquiry)}</div></div><div class="exb-footer-bottom"><p>© 2026 EXOBASIS. ${t.copyright}</p><a class="exb-back-top" href="#start"><span>${t.back}</span>${icon('up')}</a></div></div></footer>`;
}
export function noScript(page){
 const t=T[page.lang],nav=loadJSON(`src/data/navigation-${page.lang}.json`);
 return `<noscript><div class="exb-wrap exb-static-nav"><details><summary>${t.nav}</summary>${nav.map(r=>`<details><summary>${e(r.label)}</summary><ul>${r.groups.flatMap(g=>g.links).map(l=>`<li>${anchor(l.route,e(l.label))}</li>`).join('')}</ul></details>`).join('')}</details></div></noscript>`;
}
